version: "2"
linters:
  default: all
  disable:
    - containedctx
    - cyclop
    - depguard
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gocognit # check once in a while
    - godox
    - ireturn
    - mnd
    - paralleltest # duplicate of tparallel
    - tagliatelle
    - testpackage
    - wrapcheck
    - wsl # deprecated
  settings:
    dupl:
      threshold: 200
    goconst:
      min-len: 2
      min-occurrences: 3
    gocyclo:
      min-complexity: 45
    nestif:
      min-complexity: 10
    paralleltest:
      ignore-missing: true
    varnamelen:
      ignore-names:
        - err
        - id
        - i
        - j
        - xi
        - xj
        - yi
        - yj
        - tt
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
