name: Build and Deploy

on:
  push:
    branches: [development]

jobs: 
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/vzauartcc/data-parser:${{ github.sha }}
            ghcr.io/vzauartcc/data-parser:master
            ghcr.io/vzauartcc/data-parser:latest
  deploy-docker-image:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Initialize doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN_MATTHEW }}
      - name: Log into K8s cluster
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 zau-k8s
      - name: Deploy image to cluster
        run: kubectl set image deployment/data-parser-dev data-parser-dev=ghcr.io/vzauartcc/data-parser:${{ github.sha }} --record -n zau-staging-web-stack
      - name: Verify deployment
        run: kubectl rollout status deployment/data-parser-dev -n zau-staging-web-stack
